package ro.alintudor.oracle

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.graphics.*
import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.view.*
import android.widget.*
import ro.alintudor.oracle.core.OracleAccountMailer
import ro.alintudor.oracle.core.OracleApiClient
import ro.alintudor.oracle.core.OracleAuthStore
import ro.alintudor.oracle.core.OracleBootstrap
import ro.alintudor.oracle.core.OracleFirebaseMessagingService
import ro.alintudor.oracle.core.OracleKnowledgeSync
import ro.alintudor.oracle.core.OracleLoaderQuotes
import ro.alintudor.oracle.core.OracleLocalProcessor
import ro.alintudor.oracle.core.OracleRepository
import ro.alintudor.oracle.core.OracleSyncManager
import ro.alintudor.oracle.core.snapshot
import ro.alintudor.oracle.nativeui.*
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlin.math.*

/** New Start experience. Module/data logic intentionally mirrors the stable activity. */
class OracleMysticActivity : Activity() {
    companion object {
        // Same idea for the login gate: once unlocked, stays unlocked for the
        // rest of this process (matches how most local-lock apps behave —
        // re-locking only on a genuine fresh process start).
        @Volatile private var authPassedThisProcess = false
    }
    private lateinit var root: FrameLayout
    private lateinit var repository: OracleRepository
    private var currentModule: String? = null
    private val mainHandler = Handler(Looper.getMainLooper())
    private val titles = linkedMapOf("portfolio" to "PORTFOLIO", "alerts" to "ALERTS", "news" to "NEWS", "growth" to "GROWTH", "knowledge" to "KNOWLEDGE", "analysis" to "ANALYSIS", "watchlist" to "WATCHLIST", "journal" to "ACTIVITY JOURNAL")

    private val termsText = """
        Oracle is a personal, single-device application. By creating an account you agree to the following:

        1. Local use only
        This app runs entirely on your own device. There is no server, no cloud account, and nothing is transmitted to the developer. Your username, password, security question answers, and backup code are stored only on this device.

        2. No warranty
        Oracle is provided "as is," without warranty of any kind. Market data, calculations, scores, and recommendations may be inaccurate, delayed, or incomplete. The developer makes no guarantee of accuracy, availability, or fitness for any particular purpose.

        3. Your responsibility
        You are responsible for keeping your password, security question answers, and backup code safe. If you lose all of them, your account cannot be recovered — there is no server-side reset.

        4. No liability
        The developer is not liable for any loss, financial or otherwise, arising from your use of this app, including decisions made based on information it displays.

        5. Changes
        These terms may be updated at any time without notice, as this is a personal project under active development.

        See also: Disclaimer, for important information about the investment-related content in this app.
    """.trimIndent()

    private val disclaimerText = """
        Oracle is not a financial advisor, broker, or licensed investment service. Nothing shown in this app, including Growth scores, signals (BUY / HOLD / SELL), risk ratings, forecasted potential, Portfolio decisions, or Alerts, constitutes financial, investment, tax, or legal advice.

        All figures are generated by automated, local calculations based on market data that may be delayed, incomplete, or inaccurate. Past performance and any forecasted percentage are not guarantees of future results.

        Investing involves risk, including the possible loss of principal. Before making any investment decision, consult a licensed financial advisor who can consider your personal circumstances.

        The developer of this app assumes no responsibility for any financial loss resulting from its use.
    """.trimIndent()

    /** Scrollable, newest-last view of the engine log. */
    private fun showGrowthLogDialog() {
        val lines = ro.alintudor.oracle.core.OracleGrowthLog.read(this, 400)
        val panel = Color.rgb(7, 14, 28)
        val scroll = ScrollView(this).apply { setBackgroundColor(panel) }
        scroll.addView(TextView(this).apply {
            text = if (lines.isEmpty()) "Nothing recorded yet.\n\nOpen Growth to trigger a run, or wait for the nightly background scan."
                   else lines.joinToString("\n")
            textSize = 10.5f; typeface = Typeface.MONOSPACE
            setTextColor(Color.rgb(200, 208, 222)); setLineSpacing(dp(2).toFloat(), 1f)
            setPadding(dp(14), dp(14), dp(14), dp(14))
            setTextIsSelectable(true)
        })
        android.app.AlertDialog.Builder(this)
            .setTitle("Growth engine log (last ${lines.size})")
            .setView(scroll)
            .setPositiveButton("Close", null)
            .setNeutralButton("Download") { _, _ ->
                val path = ro.alintudor.oracle.core.OracleGrowthLog.export(this)
                Toast.makeText(this, if (path != null) "Growth log saved to Downloads." else "The log is empty.", Toast.LENGTH_LONG).show()
            }
            .show()
    }

    private fun offerBiometricEnrollIfNeeded(store: OracleAuthStore, onDone: () -> Unit) {
        if (store.biometricEnabled() || store.biometricOffered() || !biometricAvailable() || isFinishing || isDestroyed) {
            ro.alintudor.oracle.core.OracleGrowthLog.log(this, "AUTH", "biometric-enroll: skipped (enabled=${store.biometricEnabled()}, offered=${store.biometricOffered()}, available=${biometricAvailable()}, finishing=$isFinishing, destroyed=$isDestroyed)")
            onDone(); return
        }
        store.setBiometricOffered(true)
        ro.alintudor.oracle.core.OracleGrowthLog.log(this, "AUTH", "biometric-enroll: showing dialog")
        // A failed dialog show (window not ready, activity mid-transition)
        // must never stall the login flow — skip straight to onDone().
        runCatching {
            android.app.AlertDialog.Builder(this)
                .setTitle("Enable fingerprint unlock?")
                .setMessage("Skip typing your password next time you open Oracle — unlock with your fingerprint instead.")
                .setPositiveButton("Enable") { _, _ -> store.setBiometricEnabled(true); ro.alintudor.oracle.core.OracleGrowthLog.log(this, "AUTH", "biometric-enroll: user enabled"); onDone() }
                .setNegativeButton("Not now") { _, _ -> ro.alintudor.oracle.core.OracleGrowthLog.log(this, "AUTH", "biometric-enroll: user declined"); onDone() }
                .setCancelable(false)
                .show()
        }.onFailure { ro.alintudor.oracle.core.OracleGrowthLog.log(this, "AUTH", "biometric-enroll: dialog.show() threw: ${it.javaClass.simpleName}: ${it.message}"); onDone() }
    }

    private fun legalDialog(title: String, body: String) {
        val panel = Color.rgb(7, 14, 28)
        val muted = Color.rgb(200, 206, 220)
        val scroll = ScrollView(this).apply { setBackgroundColor(panel) }
        scroll.addView(TextView(this).apply {
            text = body; textSize = 13f; setTextColor(muted); setLineSpacing(dp(4).toFloat(), 1f)
            setPadding(dp(22), dp(18), dp(22), dp(18))
        })
        android.app.AlertDialog.Builder(this)
            .setTitle(title)
            .setView(scroll)
            .setPositiveButton("Close", null)
            .show()
    }

    private fun showTermsDialog() = legalDialog("Terms & Conditions", termsText)
    private fun showDisclaimerDialog() = legalDialog("Disclaimer", disclaimerText)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        repository = OracleRepository(this)
        window.statusBarColor = Color.rgb(3, 4, 12)
        window.navigationBarColor = Color.rgb(3, 4, 12)
        root = FrameLayout(this).apply { setBackgroundColor(Color.rgb(3, 4, 12)) }
        setContentView(root)
        if (android.os.Build.VERSION.SDK_INT >= 33) {
            onBackInvokedDispatcher.registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT) { handleBack() }
        }
        if (authPassedThisProcess) {
            proceedPastAuth()
        } else {
            runCatching { showAuthGate() }.onFailure { showFatalError("Oracle failed to start", it) }
        }
        // GROWTH warm-up starts at Android app launch, not when the user opens GROWTH —
        // deliberately independent of the auth gate, so data is ready by the time login finishes.
        Thread { runCatching { OracleLocalProcessor.refreshGrowthOnly(repository) } }.start()
    }

    // Guards against proceedPastAuth() firing twice for one login (e.g. the
    // auto-triggered biometric prompt plus a manual tap landing close
    // together) - two overlapping calls would each start their own 5s boot
    // loader timer, and whichever fires first cuts the other's countdown
    // short from the user's perspective. Reset per Activity instance, not
    // per process, so a genuine future login still gets its own loader.
    private var proceedingPastAuth = false

    private fun proceedPastAuth() {
        ro.alintudor.oracle.core.OracleGrowthLog.log(this, "AUTH", "proceedPastAuth: entered (already proceeding=$proceedingPastAuth)")
        if (proceedingPastAuth) return
        proceedingPastAuth = true
        if (android.os.Build.VERSION.SDK_INT >= 33 &&
            checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS) != android.content.pm.PackageManager.PERMISSION_GRANTED) {
            ro.alintudor.oracle.core.OracleGrowthLog.log(this, "AUTH", "proceedPastAuth: requesting POST_NOTIFICATIONS")
            runCatching { requestPermissions(arrayOf(android.Manifest.permission.POST_NOTIFICATIONS), 357) }
                .onFailure { ro.alintudor.oracle.core.OracleGrowthLog.log(this, "AUTH", "proceedPastAuth: requestPermissions threw: ${it.javaClass.simpleName}: ${it.message}") }
        }
        runCatching {
            OracleBootstrap.ensure(repository)
            OracleKnowledgeSync.scheduleNextCheck(this)
            ro.alintudor.oracle.core.OracleAlertCheckReceiver.schedule(this)
            ro.alintudor.oracle.core.OracleGrowthScanReceiver.schedule(this)
            // If today's full-universe scan hasn't run yet (fresh install, or
            // the phone was off overnight), start it now in the background.
            ro.alintudor.oracle.core.OracleGrowthScanReceiver.scanNowIfMissing(this)
            ro.alintudor.oracle.core.OracleGrowthLog.log(this, "AUTH", "proceedPastAuth: showing boot loader")
            showBootLoader()
        }.onFailure { proceedingPastAuth = false; ro.alintudor.oracle.core.OracleGrowthLog.log(this, "AUTH", "proceedPastAuth: FAILED: ${it.javaClass.simpleName}: ${it.message}"); showFatalError("Oracle failed to start", it) }
    }

    // ---------------------------------------------------------------------
    // Account gate — server-backed login/register/recovery on alintudor.ro
    // (OracleApiClient), with a local session token (OracleAuthStore) and
    // optional biometric unlock as a shortcut to reusing that token without
    // retyping the password. Runs before the boot loader on every fresh
    // process start.
    // ---------------------------------------------------------------------

    private fun showAuthGate() {
        // Accounts live on the server now — always start at Login (with a
        // path to Register), the way most server-backed apps work, rather
        // than deciding locally whether an account "exists".
        showLogin(OracleAuthStore(this))
    }

    @Suppress("DEPRECATION")
    private fun biometricAvailable(): Boolean {
        if (android.os.Build.VERSION.SDK_INT < 29) return false
        return runCatching {
            val manager = getSystemService(android.hardware.biometrics.BiometricManager::class.java)
            manager?.canAuthenticate() == android.hardware.biometrics.BiometricManager.BIOMETRIC_SUCCESS
        }.getOrDefault(false)
    }

    private fun showBiometricPrompt(onSuccess: () -> Unit) {
        if (android.os.Build.VERSION.SDK_INT < 28) return
        val executor = mainExecutor
        val prompt = android.hardware.biometrics.BiometricPrompt.Builder(this)
            .setTitle("Unlock Oracle")
            .setSubtitle("Use your fingerprint or face to continue")
            .setNegativeButton("Use password instead", executor) { _, _ -> }
            .build()
        runCatching {
            prompt.authenticate(android.os.CancellationSignal(), executor, object : android.hardware.biometrics.BiometricPrompt.AuthenticationCallback() {
                override fun onAuthenticationSucceeded(result: android.hardware.biometrics.BiometricPrompt.AuthenticationResult) { onSuccess() }
            })
        }
    }

    private fun authField(container: LinearLayout, label: String, muted: Int, panel: Int, border: Int, isPassword: Boolean = false, onAutofilled: ((View) -> Unit)? = null): EditText {
        container.addView(TextView(this).apply { text = label; textSize = 11f; setTextColor(muted); setPadding(dp(2), dp(10), 0, dp(4)) })
        // Plain EditText, unless a caller wants to know about genuine system
        // autofill specifically (as opposed to manual typing) — overriding
        // View.autofill() is the one hook Android fires only for that.
        val edit = if (onAutofilled != null) {
            object : EditText(this) {
                override fun autofill(value: android.view.autofill.AutofillValue) {
                    super.autofill(value)
                    onAutofilled(this)
                }
            }
        } else EditText(this)
        edit.apply {
            setTextColor(Color.WHITE); textSize = 15f; setSingleLine(true)
            if (isPassword) inputType = android.text.InputType.TYPE_CLASS_TEXT or android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD
            background = GradientDrawable().apply { setColor(panel); cornerRadius = dp(10).toFloat(); setStroke(dp(1), border) }
            setPadding(dp(12), dp(10), dp(12), dp(10))
            if (onAutofilled != null) {
                // Fallback for autofill services that don't go through the
                // standard View.autofill() hook (Samsung Pass has been known
                // not to, on some OS versions) — a jump of more than one
                // character in a single change is never manual keystroke
                // typing, so it's a reliable stand-in signal either way.
                addTextChangedListener(object : android.text.TextWatcher {
                    override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {}
                    override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) { if (count > 1) onAutofilled(this@apply) }
                    override fun afterTextChanged(s: android.text.Editable?) {}
                })
            }
        }
        container.addView(edit, LinearLayout.LayoutParams(-1, -2))
        return edit
    }

    private fun hideKeyboard(view: View) {
        // Posted with a short delay: if fired in the exact same instant as
        // the autofill event, the system's own focus handling for that
        // event can immediately re-show the keyboard right after, undoing
        // an immediate call. Clearing focus too, not just hiding, is the
        // more forceful combination that actually sticks.
        view.postDelayed({
            val imm = getSystemService(Context.INPUT_METHOD_SERVICE) as android.view.inputmethod.InputMethodManager
            imm.hideSoftInputFromWindow(view.windowToken, 0)
            view.clearFocus()
        }, 100L)
    }

    private fun showRegister(store: OracleAuthStore) {
        root.removeAllViews()
        val bg = Color.rgb(3, 4, 12); val panel = Color.rgb(7, 14, 28); val border = Color.rgb(49, 82, 125)
        val muted = Color.rgb(165, 174, 195); val green = Color.rgb(105, 245, 35); val red = Color.rgb(255, 90, 90)

        val scroll = ScrollView(this).apply { setBackgroundColor(bg); isFillViewport = true }
        val card = LinearLayout(this).apply { orientation = LinearLayout.VERTICAL; setPadding(dp(28), dp(40), dp(28), dp(40)) }

        card.addView(ImageView(this).apply { setImageResource(R.drawable.ic_oracle); scaleType = ImageView.ScaleType.CENTER_INSIDE },
            LinearLayout.LayoutParams(dp(64), dp(64)).apply { gravity = Gravity.CENTER; bottomMargin = dp(12) })
        card.addView(TextView(this).apply { text = "CREATE YOUR ACCOUNT"; textSize = 20f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER; setTextColor(green) })
        card.addView(TextView(this).apply {
            text = "Your account is created on alintudor.ro — log back into it any time, on this device or after a reinstall."
            textSize = 12f; gravity = Gravity.CENTER; setTextColor(muted); setPadding(dp(20), dp(6), dp(20), dp(26))
        })

        val usernameField = authField(card, "USERNAME", muted, panel, border)
        val passwordField = authField(card, "PASSWORD", muted, panel, border, isPassword = true)
        val confirmField = authField(card, "CONFIRM PASSWORD", muted, panel, border, isPassword = true)

        card.addView(TextView(this).apply {
            text = "SECURITY QUESTIONS — answer any ${OracleAuthStore.REQUIRED_SECURITY_ANSWERS} of the ${OracleAuthStore.SECURITY_QUESTIONS.size} below"
            textSize = 11f; setTextColor(muted); setPadding(dp(2), dp(18), 0, dp(4))
        })
        val questionAnswerFields = OracleAuthStore.SECURITY_QUESTIONS.mapIndexed { index, question ->
            index to authField(card, question, muted, panel, border)
        }.toMap()

        val notifyEmailField = authField(card, "NOTIFICATION EMAIL (optional — get an email when this account is created)", muted, panel, border)

        var biometricWanted = false
        if (biometricAvailable()) {
            val toggle = TextView(this).apply {
                text = "🔒  ENABLE BIOMETRIC UNLOCK"; textSize = 12f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
                setTextColor(muted)
                background = GradientDrawable().apply { setColor(panel); cornerRadius = dp(10).toFloat(); setStroke(dp(1), border) }
                setPadding(0, dp(12), 0, dp(12))
                isClickable = true; isFocusable = true
                setOnClickListener {
                    biometricWanted = !biometricWanted
                    setTextColor(if (biometricWanted) green else muted)
                    background = GradientDrawable().apply { setColor(panel); cornerRadius = dp(10).toFloat(); setStroke(dp(1), if (biometricWanted) green else border) }
                }
            }
            card.addView(toggle, LinearLayout.LayoutParams(-1, -2).apply { topMargin = dp(18) })
        }

        val termsCheckbox = CheckBox(this).apply {
            text = "I accept the Terms & Conditions"
            textSize = 12f; setTextColor(muted)
            buttonTintList = android.content.res.ColorStateList.valueOf(green)
        }
        val termsRow = LinearLayout(this).apply { orientation = LinearLayout.HORIZONTAL; gravity = Gravity.CENTER_VERTICAL; setPadding(0, dp(16), 0, 0) }
        termsRow.addView(termsCheckbox, LinearLayout.LayoutParams(0, -2, 1f))
        termsRow.addView(TextView(this).apply {
            text = "View"; textSize = 12f; typeface = Typeface.DEFAULT_BOLD; setTextColor(Color.rgb(75, 225, 255))
            isClickable = true; isFocusable = true
            setOnClickListener { showTermsDialog() }
        })
        card.addView(termsRow)

        val error = TextView(this).apply { textSize = 12f; setTextColor(red); gravity = Gravity.CENTER; setPadding(0, dp(14), 0, 0) }
        card.addView(error)

        val createButton = TextView(this).apply {
            text = "CREATE ACCOUNT"; textSize = 14f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setTextColor(Color.WHITE)
            background = GradientDrawable().apply { setColor(Color.rgb(20, 90, 60)); cornerRadius = dp(12).toFloat() }
            setPadding(0, dp(15), 0, dp(15))
            isClickable = true; isFocusable = true
        }
        createButton.setOnClickListener {
            val username = usernameField.text.toString().trim()
            val password = passwordField.text.toString()
            val confirm = confirmField.text.toString()
            val answeredCount = questionAnswerFields.values.count { it.text.toString().isNotBlank() }
            error.text = when {
                username.isBlank() -> "Enter a username."
                password.length < 8 -> "Password needs at least 8 characters."
                password != confirm -> "Passwords don't match."
                answeredCount < OracleAuthStore.REQUIRED_SECURITY_ANSWERS -> "Answer at least ${OracleAuthStore.REQUIRED_SECURITY_ANSWERS} security questions — they're the only way to reset your password later."
                !termsCheckbox.isChecked -> "You need to accept the Terms & Conditions to continue."
                else -> ""
            }
            if (error.text.isNotEmpty()) return@setOnClickListener
            createButton.isEnabled = false; createButton.text = "CREATING ACCOUNT…"
            val answers = questionAnswerFields.mapValues { entry -> entry.value.text.toString() }.filterValues { it.isNotBlank() }
            val notifyEmail = notifyEmailField.text.toString().trim()
            Thread {
                val result = OracleApiClient.register(username, password, answers, notifyEmail)
                runOnUiThread {
                    result.onSuccess { pair ->
                        val (token, backupCode) = pair
                        if (token.isBlank()) {
                            // Server-side approval flow: the account exists but the
                            // owner has to approve it before the first login.
                            android.app.AlertDialog.Builder(this@OracleMysticActivity)
                                .setTitle("Account created \u2014 awaiting approval")
                                .setMessage("Thanks, $username. New accounts are approved by hand. You'll be able to log in once it's approved${if (notifyEmail.isNotBlank()) " — we'll email $notifyEmail" else ""}.\n\nYour backup code: $backupCode\nKeep it — it's the only way to reset your password.")
                                .setPositiveButton("OK") { _, _ -> showLogin(store) }
                                .setCancelable(false).show()
                            return@onSuccess
                        }
                        store.saveSession(username, token)
                        store.setBiometricEnabled(biometricWanted)
                        store.setBiometricOffered(true)
                        OracleFirebaseMessagingService.registerCurrentToken(this@OracleMysticActivity)
                        if (notifyEmail.isNotBlank()) {
                            store.setNotificationEmail(notifyEmail)
                            OracleAccountMailer.open(this@OracleMysticActivity, notifyEmail, username, token)
                        }
                        showBackupCodeReveal(backupCode)
                    }.onFailure {
                        createButton.isEnabled = true; createButton.text = "CREATE ACCOUNT"
                        error.text = "Couldn't create the account: ${it.message}"
                    }
                }
            }.start()
        }
        card.addView(createButton, LinearLayout.LayoutParams(-1, -2).apply { topMargin = dp(20) })

        card.addView(TextView(this).apply {
            text = "Already have an account? Log in"; textSize = 12f; gravity = Gravity.CENTER; setTextColor(muted); setPadding(0, dp(18), 0, 0)
            isClickable = true; isFocusable = true
            setOnClickListener { showLogin(store) }
        })

        scroll.addView(card)
        root.addView(scroll, FrameLayout.LayoutParams(-1, -1))
    }

    private fun showBackupCodeReveal(code: String) {
        root.removeAllViews()
        val bg = Color.rgb(3, 4, 12); val panel = Color.rgb(7, 14, 28)
        val muted = Color.rgb(165, 174, 195); val gold = Color.rgb(255, 205, 55)

        val scroll = ScrollView(this).apply { setBackgroundColor(bg); isFillViewport = true }
        val card = LinearLayout(this).apply { orientation = LinearLayout.VERTICAL; gravity = Gravity.CENTER; setPadding(dp(28), dp(40), dp(28), dp(40)) }

        card.addView(TextView(this).apply { text = "SAVE YOUR BACKUP CODE"; textSize = 19f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER; setTextColor(gold) })
        card.addView(TextView(this).apply {
            text = "This is the only way to reset your password if you ever forget both it and your security answers. It will not be shown again — write it down now."
            textSize = 12f; gravity = Gravity.CENTER; setTextColor(muted); setPadding(dp(10), dp(10), dp(10), dp(26))
        })
        card.addView(TextView(this).apply {
            text = code; textSize = 24f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER; setTextColor(Color.WHITE)
            letterSpacing = 0.03f
            background = GradientDrawable().apply { setColor(panel); cornerRadius = dp(12).toFloat(); setStroke(dp(1), gold) }
            setPadding(dp(16), dp(22), dp(16), dp(22))
        })
        card.addView(TextView(this).apply {
            text = "I'VE SAVED IT — CONTINUE"; textSize = 14f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setTextColor(Color.WHITE)
            background = GradientDrawable().apply { setColor(Color.rgb(20, 90, 60)); cornerRadius = dp(12).toFloat() }
            setPadding(0, dp(15), 0, dp(15))
            isClickable = true; isFocusable = true
            setOnClickListener { authPassedThisProcess = true; proceedPastAuth() }
        }, LinearLayout.LayoutParams(-1, -2).apply { topMargin = dp(28) })

        scroll.addView(card)
        root.addView(scroll, FrameLayout.LayoutParams(-1, -1))
    }

    private fun showLogin(store: OracleAuthStore) {
        root.removeAllViews()
        val bg = Color.rgb(3, 4, 12); val panel = Color.rgb(7, 14, 28); val border = Color.rgb(49, 82, 125)
        val muted = Color.rgb(165, 174, 195); val gold = Color.rgb(255, 205, 55); val green = Color.rgb(105, 245, 35); val red = Color.rgb(255, 90, 90)

        val scroll = ScrollView(this).apply { setBackgroundColor(bg); isFillViewport = true }
        val card = LinearLayout(this).apply { orientation = LinearLayout.VERTICAL; gravity = Gravity.CENTER; setPadding(dp(28), dp(40), dp(28), dp(40)) }

        card.addView(ImageView(this).apply {
            setImageResource(R.drawable.ic_oracle); scaleType = ImageView.ScaleType.CENTER_INSIDE
            val pulseX = android.animation.PropertyValuesHolder.ofFloat(View.SCALE_X, 1f, 1.06f, 1f)
            val pulseY = android.animation.PropertyValuesHolder.ofFloat(View.SCALE_Y, 1f, 1.06f, 1f)
            android.animation.ObjectAnimator.ofPropertyValuesHolder(this, pulseX, pulseY).apply {
                duration = 2200L
                repeatCount = android.animation.ObjectAnimator.INFINITE
                interpolator = android.view.animation.AccelerateDecelerateInterpolator()
            }.start()
        }, LinearLayout.LayoutParams(dp(72), dp(72)).apply { gravity = Gravity.CENTER; bottomMargin = dp(10) })
        card.addView(TextView(this).apply { text = "ORACLE"; textSize = 24f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER; setTextColor(green) })
        card.addView(TextView(this).apply {
            text = if (store.username().isNotBlank()) "Welcome back, ${store.username()}" else "Log in to your account"
            textSize = 13f; gravity = Gravity.CENTER; setTextColor(muted); setPadding(0, dp(4), 0, dp(28))
        })

        val usernameField = authField(card, "USERNAME", muted, panel, border).apply { setText(store.username()) }
        var afterPasswordAutofill: ((View) -> Unit)? = null
        val passwordField = authField(card, "PASSWORD", muted, panel, border, isPassword = true, onAutofilled = { view -> afterPasswordAutofill?.invoke(view) })

        val error = TextView(this).apply { textSize = 12f; setTextColor(red); gravity = Gravity.CENTER; setPadding(0, dp(12), 0, 0) }
        card.addView(error)

        val loginButton = TextView(this).apply {
            text = "LOG IN"; textSize = 14f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setTextColor(Color.WHITE)
            background = GradientDrawable().apply { setColor(Color.rgb(20, 90, 60)); cornerRadius = dp(12).toFloat() }
            setPadding(0, dp(15), 0, dp(15))
            isClickable = true; isFocusable = true
        }
        loginButton.setOnClickListener {
            val username = usernameField.text.toString().trim()
            val password = passwordField.text.toString()
            if (username.isBlank() || password.isBlank()) { error.text = "Enter your username and password."; return@setOnClickListener }
            loginButton.isEnabled = false; loginButton.text = "LOGGING IN…"
            ro.alintudor.oracle.core.OracleGrowthLog.log(this, "AUTH", "login: button tapped for user=$username")
            Thread {
                val result = OracleApiClient.login(username, password)
                ro.alintudor.oracle.core.OracleGrowthLog.log(this@OracleMysticActivity, "AUTH", "login: API call returned, success=${result.isSuccess}")
                runOnUiThread {
                    ro.alintudor.oracle.core.OracleGrowthLog.log(this@OracleMysticActivity, "AUTH", "login: on UI thread with result")
                    result.onSuccess { token ->
                        store.saveSession(username, token)
                        ro.alintudor.oracle.core.OracleGrowthLog.log(this@OracleMysticActivity, "AUTH", "login: session saved, registering push token")
                        OracleFirebaseMessagingService.registerCurrentToken(this@OracleMysticActivity)
                        ro.alintudor.oracle.core.OracleGrowthLog.log(this@OracleMysticActivity, "AUTH", "login: starting pullAll")
                        OracleSyncManager.pullAll(this@OracleMysticActivity, token) { pullSuccess ->
                            ro.alintudor.oracle.core.OracleGrowthLog.log(this@OracleMysticActivity, "AUTH", "login: pullAll onDone, success=$pullSuccess")
                            offerBiometricEnrollIfNeeded(store) {
                                ro.alintudor.oracle.core.OracleGrowthLog.log(this@OracleMysticActivity, "AUTH", "login: biometric-enroll step done, calling proceedPastAuth")
                                authPassedThisProcess = true
                                proceedPastAuth()
                            }
                        }
                    }.onFailure {
                        loginButton.isEnabled = true; loginButton.text = "LOG IN"
                        val msg = it.message ?: ""
                        error.text = when {
                            msg.contains("pending", true) || msg.contains("approv", true) -> "Your account is awaiting approval by the owner. You'll be notified when it's ready."
                            msg.contains("rejected", true) || msg.contains("declined", true) -> "This account was not approved."
                            msg.isNotBlank() -> msg
                            else -> "Wrong username or password."
                        }
                    }
                }
            }.start()
        }
        // Autofill filled the password — if a username is present too, submit
        // on its own, no tap needed. Only fires for genuine autofill, never
        // for manual typing (see authField's onAutofilled contract).
        afterPasswordAutofill = { view ->
            hideKeyboard(view)
            if (usernameField.text.toString().isNotBlank() && loginButton.isEnabled) {
                view.postDelayed({ loginButton.performClick() }, 150L)
            }
        }
        card.addView(loginButton, LinearLayout.LayoutParams(-1, -2).apply { topMargin = dp(18) })

        if (store.biometricEnabled() && store.hasSession() && biometricAvailable()) {
            card.addView(TextView(this).apply {
                text = "🔒  USE BIOMETRIC UNLOCK"; textSize = 13f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
                setTextColor(gold)
                background = GradientDrawable().apply { setColor(panel); cornerRadius = dp(12).toFloat(); setStroke(dp(1), gold) }
                setPadding(0, dp(14), 0, dp(14))
                isClickable = true; isFocusable = true
                setOnClickListener { showBiometricPrompt { authPassedThisProcess = true; proceedPastAuth() } }
            }, LinearLayout.LayoutParams(-1, -2).apply { topMargin = dp(12) })
        }

        card.addView(TextView(this).apply {
            text = "Don't have an account? Register"; textSize = 12f; gravity = Gravity.CENTER; setTextColor(muted); setPadding(0, dp(16), 0, 0)
            isClickable = true; isFocusable = true
            setOnClickListener { showRegister(store) }
        })
        card.addView(TextView(this).apply {
            text = "\uD83D\uDD13  TRY THE DEMO \u2014 no account needed"; textSize = 12.5f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER; setTextColor(gold); setPadding(0, dp(18), 0, 0)
            isClickable = true; isFocusable = true
            setOnClickListener {
                // A real session (e.g. from biometric) must never run
                // alongside the demo — otherwise the demo's own data
                // operations would sync against the real account.
                store.clearSession()
                ro.alintudor.oracle.core.OracleDemo.enter(this@OracleMysticActivity)
                authPassedThisProcess = true
                proceedPastAuth()
            }
        })
        card.addView(TextView(this).apply {
            text = "Forgot password?"; textSize = 12f; gravity = Gravity.CENTER; setTextColor(muted); setPadding(0, dp(14), 0, 0)
            isClickable = true; isFocusable = true
            setOnClickListener { showForgotPassword(store) }
        })
        card.addView(TextView(this).apply {
            text = "Disclaimer"; textSize = 11f; gravity = Gravity.CENTER; setTextColor(Color.rgb(125, 135, 155)); setPadding(0, dp(14), 0, 0)
            isClickable = true; isFocusable = true
            setOnClickListener { showDisclaimerDialog() }
        })

        scroll.addView(card)
        root.addView(scroll, FrameLayout.LayoutParams(-1, -1))

        if (store.biometricEnabled() && store.hasSession() && biometricAvailable()) {
            showBiometricPrompt { authPassedThisProcess = true; proceedPastAuth() }
        }
    }

    private fun showForgotPassword(store: OracleAuthStore) {
        root.removeAllViews()
        val bg = Color.rgb(3, 4, 12); val panel = Color.rgb(7, 14, 28); val border = Color.rgb(49, 82, 125)
        val muted = Color.rgb(165, 174, 195); val green = Color.rgb(105, 245, 35); val red = Color.rgb(255, 90, 90)

        val scroll = ScrollView(this).apply { setBackgroundColor(bg); isFillViewport = true }
        val card = LinearLayout(this).apply { orientation = LinearLayout.VERTICAL; setPadding(dp(28), dp(40), dp(28), dp(40)) }

        card.addView(TextView(this).apply { text = "RESET PASSWORD"; textSize = 20f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER; setTextColor(green) })
        card.addView(TextView(this).apply {
            text = "Answer the security questions you set at registration, or use your backup code."
            textSize = 12f; gravity = Gravity.CENTER; setTextColor(muted); setPadding(dp(10), dp(8), dp(10), dp(24))
        })

        val usernameField = authField(card, "USERNAME", muted, panel, border).apply { setText(store.username()) }
        card.addView(TextView(this).apply {
            text = "Fill in whichever security questions you answered at registration — leave the rest blank."
            textSize = 11f; setTextColor(muted); setPadding(0, dp(14), 0, dp(4))
        })
        val answerFields = OracleAuthStore.SECURITY_QUESTIONS.mapIndexed { index, question ->
            index to authField(card, question, muted, panel, border)
        }.toMap()

        card.addView(TextView(this).apply { text = "— OR —"; textSize = 11f; gravity = Gravity.CENTER; setTextColor(muted); setPadding(0, dp(14), 0, dp(2)) })
        val backupField = authField(card, "BACKUP CODE (from registration)", muted, panel, border)
        val newPasswordField = authField(card, "NEW PASSWORD", muted, panel, border, isPassword = true)
        val confirmField = authField(card, "CONFIRM NEW PASSWORD", muted, panel, border, isPassword = true)

        val error = TextView(this).apply { textSize = 12f; setTextColor(red); gravity = Gravity.CENTER; setPadding(0, dp(12), 0, 0) }
        card.addView(error)

        val resetButton = TextView(this).apply {
            text = "RESET PASSWORD"; textSize = 14f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setTextColor(Color.WHITE)
            background = GradientDrawable().apply { setColor(Color.rgb(20, 90, 60)); cornerRadius = dp(12).toFloat() }
            setPadding(0, dp(15), 0, dp(15))
            isClickable = true; isFocusable = true
        }
        resetButton.setOnClickListener {
            val username = usernameField.text.toString().trim()
            val answers = answerFields.mapValues { it.value.text.toString() }.filterValues { it.isNotBlank() }
            val backupCode = backupField.text.toString()
            val newPassword = newPasswordField.text.toString()
            val confirm = confirmField.text.toString()
            error.text = when {
                username.isBlank() -> "Enter your username."
                newPassword.length < 8 -> "Password needs at least 8 characters."
                newPassword != confirm -> "Passwords don't match."
                answers.isEmpty() && backupCode.isBlank() -> "Answer at least one security question, or provide your backup code."
                else -> ""
            }
            if (error.text.isNotEmpty()) return@setOnClickListener
            resetButton.isEnabled = false; resetButton.text = "RESETTING…"
            Thread {
                val result = OracleApiClient.forgotPassword(username, answers, backupCode, newPassword)
                runOnUiThread {
                    result.onSuccess {
                        Toast.makeText(this@OracleMysticActivity, "Password updated — log in with your new password.", Toast.LENGTH_LONG).show()
                        showLogin(store)
                    }.onFailure {
                        resetButton.isEnabled = true; resetButton.text = "RESET PASSWORD"
                        error.text = it.message ?: "Those answers or that backup code don't match."
                    }
                }
            }.start()
        }
        card.addView(resetButton, LinearLayout.LayoutParams(-1, -2).apply { topMargin = dp(20) })

        card.addView(TextView(this).apply {
            text = "Back to login"; textSize = 12f; gravity = Gravity.CENTER; setTextColor(muted); setPadding(0, dp(18), 0, 0)
            isClickable = true; isFocusable = true
            setOnClickListener { showLogin(store) }
        })

        scroll.addView(card)
        root.addView(scroll, FrameLayout.LayoutParams(-1, -1))
    }

    /**
     * Boot loader shown for ~5s between app open and the START hub, visually
     * matching the GROWTH loading card (spinning Oracle icon + percentage bar
     * + rotating investor quotes). GROWTH data is already loading in the
     * background during this time.
     */
    private fun showBootLoader() {
        root.removeAllViews()
        val bg = Color.rgb(3, 4, 12)
        val muted = Color.rgb(165, 174, 195)
        val cyan = Color.rgb(75, 225, 255)
        val gold = Color.rgb(255, 205, 55)
        val green = Color.rgb(105, 245, 35)

        // Full-screen card: the whole background IS the card now.
        val card = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            gravity = Gravity.CENTER
            setPadding(dp(36), dp(36), dp(36), dp(36))
            setBackgroundColor(bg)
        }

        val spinner = ImageView(this).apply {
            setImageResource(R.drawable.ic_oracle)
            contentDescription = "Oracle is starting up"
            scaleType = ImageView.ScaleType.CENTER_INSIDE
            android.animation.ObjectAnimator.ofFloat(this, View.ROTATION, 0f, 360f).apply {
                duration = 1100L
                repeatCount = android.animation.ObjectAnimator.INFINITE
                interpolator = android.view.animation.LinearInterpolator()
            }.start()
        }
        card.addView(spinner, LinearLayout.LayoutParams(dp(100), dp(100)).apply { gravity = Gravity.CENTER })
        card.addView(TextView(this).apply {
            text = "ORACLE"; textSize = 30f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setTextColor(green); setPadding(0, dp(18), 0, dp(6))
        })
        card.addView(TextView(this).apply {
            text = "Getting things ready…"; textSize = 16f; gravity = Gravity.CENTER
            setTextColor(muted); setPadding(0, 0, 0, dp(26))
        })

        val percentLabel = TextView(this).apply {
            text = "0%"; textSize = 18f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setTextColor(cyan); setPadding(0, 0, 0, dp(10))
        }
        card.addView(percentLabel)
        val progressBar = ProgressBar(this, null, android.R.attr.progressBarStyleHorizontal).apply {
            max = 100; progress = 0; isIndeterminate = false
        }
        card.addView(progressBar, LinearLayout.LayoutParams(dp(280), dp(10)))

        // Same rotating investor quotes as the GROWTH loader (OracleLoaderQuotes),
        // just cycling faster since the boot loader only runs for 5s total.
        // Bigger and colored, as requested — the quotation marks are part of the
        // quote strings themselves (OracleLoaderQuotes).
        var currentQuote = OracleLoaderQuotes.random()
        val quoteLabel = TextView(this).apply {
            text = OracleLoaderQuotes.spanned(currentQuote, gold, muted)
            textSize = 21f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setPadding(dp(12), 0, dp(12), 0)
            setLineSpacing(0f, 1.2f)
            maxLines = 4
        }
        // Fixed height (not wrap_content): a 1-line quote and a 4-line quote
        // both reserve the same space, so the spinner/percent/bar above never
        // shift position as the rotating quotes change length.
        card.addView(quoteLabel, LinearLayout.LayoutParams(-1, dp(150)).apply { topMargin = dp(24) })

        root.addView(card, FrameLayout.LayoutParams(-1, -1))

        val bootDurationMs = 5_000L
        android.animation.ValueAnimator.ofInt(0, 100).apply {
            duration = bootDurationMs
            interpolator = android.view.animation.LinearInterpolator()
            addUpdateListener { anim ->
                val v = anim.animatedValue as Int
                progressBar.progress = v
                percentLabel.text = "$v%"
            }
        }.start()

        val quoteRunnable = object : Runnable {
            override fun run() {
                currentQuote = OracleLoaderQuotes.random(excluding = currentQuote)
                quoteLabel.text = OracleLoaderQuotes.spanned(currentQuote, gold, muted)
                mainHandler.postDelayed(this, 1_800L)
            }
        }
        mainHandler.postDelayed(quoteRunnable, 1_800L)

        mainHandler.postDelayed({
            mainHandler.removeCallbacks(quoteRunnable)
            if (!isFinishing) { showHub(); consumePendingModuleIntent() }
        }, bootDurationMs)
    }

    private fun checkAlertsStatusSilently(hero: OracleMysticStartView) {
        val notificationsEnabled = runCatching {
            (getSystemService(Context.NOTIFICATION_SERVICE) as android.app.NotificationManager).areNotificationsEnabled()
        }.getOrDefault(false)
        if (!notificationsEnabled) {
            hero.setAlertsStatus("ALERTS OFF", Color.rgb(150, 150, 150))
            return
        }
        // Local-only check: does this device actually have a working FCM
        // token available? No network call to our own server, no push or
        // email sent — purely "is the plumbing on this device functional".
        runCatching {
            com.google.firebase.messaging.FirebaseMessaging.getInstance().token.addOnCompleteListener { task ->
                runOnUiThread {
                    val ok = task.isSuccessful && !task.result.isNullOrBlank()
                    hero.setAlertsStatus(if (ok) "ALERTS ON" else "ALERTS OFF", if (ok) Color.rgb(105, 245, 35) else Color.rgb(150, 150, 150))
                }
            }
        }.onFailure {
            hero.setAlertsStatus("ALERTS OFF", Color.rgb(150, 150, 150))
        }
    }

    private fun showHub() {
        currentModule = null
        root.removeAllViews()
        val scroll = ScrollView(this).apply { isFillViewport = true; setBackgroundColor(Color.rgb(3, 4, 12)) }
        val page = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            setPadding(dp(8), dp(40), dp(8), dp(20))
        }
        val hero = OracleMysticStartView(this) { openModule(it) }
        val heroHeight = (resources.displayMetrics.heightPixels * 0.86f).toInt().coerceAtLeast(dp(660))
        page.addView(hero, LinearLayout.LayoutParams(-1, heroHeight))
        scroll.addView(page)
        root.addView(scroll, FrameLayout.LayoutParams(-1, -1))
        checkAlertsStatusSilently(hero)
    }

    /** Shared by the START tile and (defensively) by TOOLS' own button — the
     *  exact same dialog either way, so exiting the demo behaves identically
     *  no matter which door was used to reach it. */
    private fun confirmExitDemo() {
        android.app.AlertDialog.Builder(this)
            .setTitle("Exit the demo?")
            .setMessage("The sample portfolio is removed. Create an account to keep your own.")
            .setPositiveButton("Exit") { _, _ ->
                ro.alintudor.oracle.core.OracleGrowthLog.log(this, "AUTH", "exit-demo confirmed")
                val store = OracleAuthStore(this)
                ro.alintudor.oracle.core.OracleDemo.exit(this)
                store.clearSession()
                authPassedThisProcess = false
                currentModule = null
                // Posted rather than called inline: this dialog's own window
                // is still tearing down when this callback runs, and tearing
                // down `root` (then possibly showing a second dialog moments
                // later, e.g. biometric enrollment) right on top of that was
                // the one path where login got stuck on "LOGGING IN..."
                // until the app was backgrounded and resumed.
                root.post { ro.alintudor.oracle.core.OracleGrowthLog.log(this, "AUTH", "exit-demo: showing login screen (posted)"); showLogin(store) }
            }
            .setNegativeButton("Cancel", null)
            .show()
    }

    private fun showBackupScreen() {
        // TOOLS is closed to a demo visitor — reaching this by any path (deep
        // link, back-stack, a stale reference) redirects straight to the exit
        // prompt instead of ever rendering the screen.
        if (ro.alintudor.oracle.core.OracleDemo.active(this)) { confirmExitDemo(); return }
        root.removeAllViews()
        val bg = Color.rgb(3, 4, 12); val panel = Color.rgb(7, 14, 28); val border = Color.rgb(49, 82, 125)
        val muted = Color.rgb(165, 174, 195); val gold = Color.rgb(255, 205, 55); val green = Color.rgb(105, 245, 35)

        val scroll = ScrollView(this).apply { setBackgroundColor(bg); isFillViewport = true }
        val card = LinearLayout(this).apply { orientation = LinearLayout.VERTICAL; setPadding(dp(28), dp(40), dp(28), dp(40)) }

        card.addView(TextView(this).apply { text = "TOOLS"; textSize = 20f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER; setTextColor(gold) })
        card.addView(TextView(this).apply {
            text = "Your data syncs to your account automatically — nothing to manage here."
            textSize = 12f; setTextColor(muted); gravity = Gravity.CENTER; setPadding(0, dp(10), 0, dp(26))
        })

        val pushStatus = TextView(this).apply { textSize = 12f; gravity = Gravity.CENTER; setPadding(0, dp(10), 0, 0) }
        card.addView(TextView(this).apply {
            text = "SEND TEST NOTIFICATION"; textSize = 13f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setTextColor(Color.rgb(75, 225, 255))
            background = GradientDrawable().apply { setColor(panel); cornerRadius = dp(12).toFloat(); setStroke(dp(1), Color.rgb(75, 225, 255)) }
            setPadding(0, dp(14), 0, dp(14))
            isClickable = true; isFocusable = true
            setOnClickListener {
                val auth = OracleAuthStore(this@OracleMysticActivity)
                if (!auth.hasSession()) { pushStatus.setTextColor(Color.rgb(255, 90, 90)); pushStatus.text = "Not logged in."; return@setOnClickListener }
                pushStatus.setTextColor(muted); pushStatus.text = "Sending…"
                Thread {
                    val result = OracleApiClient.notify(auth.token(), "Oracle test notification", "If you see this on your phone, push notifications are working correctly.")
                    runOnUiThread {
                        result.onSuccess { response ->
                            val push = response.optJSONObject("push")
                            val pushOk = push?.optBoolean("ok", false) ?: false
                            if (pushOk) {
                                pushStatus.setTextColor(green); pushStatus.text = "Email sent, push sent — check your phone."
                            } else {
                                val reason = push?.optString("error")?.takeIf { it.isNotBlank() } ?: "unknown reason"
                                pushStatus.setTextColor(Color.rgb(255, 205, 55))
                                pushStatus.text = "Email sent, but push failed: $reason"
                            }
                        }.onFailure { pushStatus.setTextColor(Color.rgb(255, 90, 90)); pushStatus.text = "Failed: ${it.message}" }
                    }
                }.start()
            }
        }, LinearLayout.LayoutParams(-1, -2).apply { topMargin = dp(20) })
        card.addView(pushStatus)

        val batteryStatus = TextView(this).apply { textSize = 12f; gravity = Gravity.CENTER; setPadding(0, dp(10), 0, 0) }
        card.addView(TextView(this).apply {
            text = "WIDGET UPDATE RELIABILITY"; textSize = 14f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setTextColor(gold); setPadding(0, dp(28), 0, dp(6))
        })
        card.addView(TextView(this).apply {
            text = "The Growth widget refreshes itself every 3 minutes via its own alarm. Android's battery-saving mode can still delay that while the screen is off for a while. Exempting Oracle from battery optimization keeps it closer to the 3-minute cadence — one tap, reversible any time from your phone's own Settings."
            textSize = 11f; setTextColor(muted); setPadding(0, 0, 0, dp(14))
        })
        card.addView(TextView(this).apply {
            text = "DISABLE BATTERY OPTIMIZATION FOR ORACLE"; textSize = 13f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setTextColor(Color.rgb(105, 245, 35))
            background = GradientDrawable().apply { setColor(panel); cornerRadius = dp(12).toFloat(); setStroke(dp(1), Color.rgb(105, 245, 35)) }
            setPadding(0, dp(14), 0, dp(14))
            isClickable = true; isFocusable = true
            setOnClickListener {
                val pm = getSystemService(android.os.PowerManager::class.java)
                if (pm.isIgnoringBatteryOptimizations(packageName)) {
                    batteryStatus.setTextColor(green); batteryStatus.text = "Already exempt — the widget gets the best refresh reliability Android allows."
                } else {
                    runCatching {
                        val intent = Intent(android.provider.Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS).apply {
                            data = android.net.Uri.parse("package:$packageName")
                        }
                        startActivity(intent)
                    }.onFailure {
                        batteryStatus.setTextColor(Color.rgb(255, 90, 90))
                        batteryStatus.text = "Couldn't open the system dialog. Try Settings > Apps > Oracle > Battery instead."
                    }
                }
            }
        }, LinearLayout.LayoutParams(-1, -2))
        card.addView(batteryStatus)

        // --- Growth engine log ------------------------------------------------
        card.addView(TextView(this).apply {
            text = "GROWTH ENGINE LOG"; textSize = 14f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setTextColor(gold); setPadding(0, dp(28), 0, dp(6))
        })
        val logCount = ro.alintudor.oracle.core.OracleGrowthLog.lineCount(this)
        card.addView(TextView(this).apply {
            text = if (logCount == 0) "No entries yet. The engine writes here on every run, scan and ranking."
                   else "$logCount entries recorded — every run, universe resolution, scan, enrichment and pick."
            textSize = 11f; gravity = Gravity.CENTER; setTextColor(muted); setPadding(dp(6), 0, dp(6), dp(10))
        })
        val logRow = LinearLayout(this).apply { orientation = LinearLayout.HORIZONTAL }
        fun toolButton(label: String, color: Int, onClick: () -> Unit) = TextView(this).apply {
            text = label; textSize = 12f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER; setTextColor(color)
            background = GradientDrawable().apply { setColor(panel); cornerRadius = dp(11).toFloat(); setStroke(dp(1), color) }
            setPadding(0, dp(12), 0, dp(12)); isClickable = true; isFocusable = true
            setOnClickListener { onClick() }
        }
        logRow.addView(toolButton("VIEW", Color.rgb(55, 215, 255)) { showGrowthLogDialog() },
            LinearLayout.LayoutParams(0, -2, 1f).apply { setMargins(0, 0, dp(5), 0) })
        logRow.addView(toolButton("DOWNLOAD", green) {
            val path = ro.alintudor.oracle.core.OracleGrowthLog.export(this)
            Toast.makeText(this, if (path != null) "Growth log saved to Downloads." else "The log is empty — nothing to export yet.", Toast.LENGTH_LONG).show()
        }, LinearLayout.LayoutParams(0, -2, 1f).apply { setMargins(dp(5), 0, dp(5), 0) })
        logRow.addView(toolButton("CLEAR", Color.rgb(255, 140, 140)) {
            android.app.AlertDialog.Builder(this)
                .setTitle("Clear the Growth log?")
                .setMessage("The recorded history of engine runs is deleted. New entries start from the next run.")
                .setPositiveButton("Clear") { _, _ ->
                    ro.alintudor.oracle.core.OracleGrowthLog.clear(this)
                    Toast.makeText(this, "Growth log cleared.", Toast.LENGTH_SHORT).show()
                    showBackupScreen()
                }
                .setNegativeButton("Cancel", null).show()
        }, LinearLayout.LayoutParams(0, -2, 1f).apply { setMargins(dp(5), 0, 0, 0) })
        card.addView(logRow, LinearLayout.LayoutParams(-1, -2))

        // --- Growth history (the "LATEST RECOMMENDATIONS" journal) ------------
        // Separate from the log above: this is the recommendation TRACK
        // RECORD itself, not the diagnostic trail of engine runs — it grows
        // by one entry per new pick, so heavy same-day testing (many
        // refreshes while the anchor doesn't change) can leave a cluttered
        // history behind that's worth being able to reset on its own.
        card.addView(TextView(this).apply {
            text = "GROWTH HISTORY"; textSize = 14f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setTextColor(gold); setPadding(0, dp(28), 0, dp(6))
        })
        val journalStore = ro.alintudor.oracle.core.OracleGrowthJournalStore(this)
        val journalCount = journalStore.load().size
        card.addView(TextView(this).apply {
            text = if (journalCount == 0) "No recorded recommendations yet."
                   else "$journalCount recommendations recorded — shown as \"Latest recommendations\" on Growth."
            textSize = 11f; gravity = Gravity.CENTER; setTextColor(muted); setPadding(dp(6), 0, dp(6), dp(10))
        })
        card.addView(toolButton("CLEAR HISTORY", Color.rgb(255, 140, 140)) {
            android.app.AlertDialog.Builder(this)
                .setTitle("Clear the Growth history?")
                .setMessage("Every past recommendation entry is deleted — this also resets the Performance track record. New entries start from the next pick.")
                .setPositiveButton("Clear") { _, _ ->
                    journalStore.clear()
                    Toast.makeText(this, "Growth history cleared.", Toast.LENGTH_SHORT).show()
                    showBackupScreen()
                }
                .setNegativeButton("Cancel", null).show()
        }, LinearLayout.LayoutParams(-1, -2))

        card.addView(TextView(this).apply {
            text = "ACCOUNT"; textSize = 14f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setTextColor(gold); setPadding(0, dp(28), 0, dp(14))
        })
        // The demo branch here is unreachable — showBackupScreen() itself
        // redirects to confirmExitDemo() before this point whenever the demo
        // is active, so a real logged-in session is the only case left.
        card.addView(TextView(this).apply {
            text = "LOG OUT"; textSize = 13f; typeface = Typeface.DEFAULT_BOLD; gravity = Gravity.CENTER
            setTextColor(Color.rgb(255, 110, 110))
            background = GradientDrawable().apply { setColor(panel); cornerRadius = dp(12).toFloat(); setStroke(dp(1), Color.rgb(255, 110, 110)) }
            setPadding(0, dp(14), 0, dp(14))
            isClickable = true; isFocusable = true
            setOnClickListener {
                android.app.AlertDialog.Builder(this@OracleMysticActivity)
                    .setTitle("Log out?")
                    .setMessage("You'll need your username and password (or fingerprint, if enabled) to log back in.")
                    .setPositiveButton("Log out") { _, _ ->
                        val store = OracleAuthStore(this@OracleMysticActivity)
                        store.clearSession()
                        authPassedThisProcess = false
                        currentModule = null
                        showLogin(store)
                    }
                    .setNegativeButton("Cancel", null)
                    .show()
            }
        }, LinearLayout.LayoutParams(-1, -2))

        card.addView(TextView(this).apply {
            text = "← Back"; textSize = 12f; gravity = Gravity.CENTER; setTextColor(muted); setPadding(0, dp(24), 0, 0)
            isClickable = true; isFocusable = true
            setOnClickListener { showHub() }
        })

        scroll.addView(card)
        root.addView(scroll, FrameLayout.LayoutParams(-1, -1))
    }

    @Deprecated("Deprecated in Java")
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode != ro.alintudor.oracle.nativeui.OraclePortfolioModule.CSV_IMPORT_REQUEST || resultCode != RESULT_OK) return
        val uri = data?.data ?: return
        Thread {
            val text = runCatching { contentResolver.openInputStream(uri)?.bufferedReader(Charsets.UTF_8)?.use { it.readText() } ?: "" }.getOrDefault("")
            val rows = runCatching { ro.alintudor.oracle.core.OracleCsvImport.parse(text) }.getOrDefault(emptyList())
            val n = if (rows.isNotEmpty()) ro.alintudor.oracle.nativeui.OraclePortfolioModule.applyImport(this, rows) else 0
            runOnUiThread {
                if (n == 0) Toast.makeText(this, "No positions recognized in that file (needs ticker, quantity and price columns).", Toast.LENGTH_LONG).show()
                else { Toast.makeText(this, "Imported $n position${if (n == 1) "" else "s"} — prices refresh now.", Toast.LENGTH_LONG).show(); currentModule = null; openModule("portfolio") }
            }
        }.start()
    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        setIntent(intent)
        // Only route straight to the requested module if this session is
        // already unlocked — otherwise a widget tap could skip the login
        // screen entirely. If not yet authenticated, the request is simply
        // left in the intent and picked up normally once login succeeds.
        if (::root.isInitialized && authPassedThisProcess) consumePendingModuleIntent()
    }

    /** Handles the widget's "open Growth directly" tap. Consumed once so
     *  rotating the screen or returning to the app later doesn't re-trigger it. */
    private fun consumePendingModuleIntent() {
        val module = intent?.getStringExtra("open_module") ?: return
        intent.removeExtra("open_module")
        openModule(module)
    }

    private fun openModule(key: String) {
        if (key == "disclaimer") { showDisclaimerDialog(); return }
        if (key == "backup") {
            if (ro.alintudor.oracle.core.OracleDemo.active(this)) { confirmExitDemo(); return }
            currentModule = "backup"; showBackupScreen(); return
        }
        // A press on the refresh button re-enters this same function with the
        // same key the screen is already showing — distinct from a genuine
        // navigation into the module, where the screen must render immediately
        // (with cached data) so it isn't blank while the background refresh runs.
        val isRefreshOfOpenScreen = currentModule == key
        currentModule = key
        if (key == "alerts" && android.os.Build.VERSION.SDK_INT >= 33 &&
            checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS) != android.content.pm.PackageManager.PERMISSION_GRANTED) {
            requestPermissions(arrayOf(android.Manifest.permission.POST_NOTIFICATIONS), 357)
        }
        // On a refresh of an already-open screen, skip this immediate render:
        // the screen already shows this exact data, so redrawing it here only
        // to redraw it again a moment later (once the background refresh below
        // lands) is a redundant rebuild.
        if (!isRefreshOfOpenScreen) runCatching { renderModule(key) }.onFailure { showModuleError(key, it) }

        // GROWTH is a live, independent module. The real launcher is
        // OracleMysticActivity, so Growth must be calculated here rather than
        // relying on the dead MainActivity path or the general refresh chain.
        if (key == "growth") {
            Thread {
                val result = runCatching { OracleLocalProcessor.refreshGrowthOnly(repository) }
                mainHandler.post {
                    if (currentModule != "growth" || isFinishing) return@post
                    result.onSuccess {
                        runCatching { renderModule("growth", reuseHost = isRefreshOfOpenScreen) }
                            .onFailure { showModuleError("growth", it) }
                    }.onFailure { error ->
                        showGrowthCalculationError(error)
                    }
                }
            }.start()
            return
        }

        if (key == "analysis") {
            // Analysis has no background refresh step, so a refresh press here
            // needs its own explicit render (the general skip above only defers
            // to a render that happens later — there is no "later" for Analysis).
            if (isRefreshOfOpenScreen) runCatching { renderModule(key, reuseHost = true) }.onFailure { showModuleError(key, it) }
            return
        }
        Thread {
            val result = runCatching { OracleLocalProcessor.refresh(repository) }
            mainHandler.post {
                if (currentModule != key || isFinishing) return@post
                // On a refresh of the already-open screen: update in place (same
                // ScrollView instance, no rebuild) and skip entrance animations —
                // reusing the exact same View is what actually guarantees the
                // scroll position can't move, rather than relying on restoring a
                // saved offset into a freshly built one. A genuine navigation
                // into the module still gets the normal fresh build + entrance.
                result.onSuccess { runCatching { renderModule(key, silent = isRefreshOfOpenScreen, reuseHost = isRefreshOfOpenScreen) }.onFailure { showModuleError(key, it) } }
                    .onFailure { Toast.makeText(this, "Local refresh failed: ${it.message ?: it.javaClass.simpleName}", Toast.LENGTH_LONG).show() }
            }
        }.start()
    }

    /** The currently mounted module shell, kept so a refresh can update its
     *  content in place (reuseHost) instead of tearing down and rebuilding the
     *  ScrollView — the only way to guarantee the scroll position truly cannot
     *  move. Always discarded on the next fresh navigation (reuseHost = false
     *  rebuilds and replaces it), and implicitly invalidated by showHub()
     *  setting currentModule = null, which makes isRefreshOfOpenScreen false
     *  for any subsequent openModule() call. */
    private var activeHost: OracleNativeModule? = null

    private fun renderModule(key: String, silent: Boolean = false, reuseHost: Boolean = false) {
        val moduleTitle = titles[key] ?: key.uppercase()
        val existing = activeHost
        val host = if (reuseHost && existing != null) existing else {
            root.removeAllViews()
            val fresh = OracleNativeModule(this, moduleTitle, { showHub() }, { openModule(key) }, moduleKey = key)
            root.addView(fresh.root, FrameLayout.LayoutParams(-1, -1))
            activeHost = fresh
            fresh
        }
        val data = repository.snapshot()
        when (key) {
            "portfolio" -> OraclePortfolioModule(host).render(data.positions, silent)
            "alerts" -> OracleAlertsModule(host).render(data.alerts)
            "news" -> OracleNewsModule(host).render(data.news)
            "journal" -> OracleJournalModule(host).render(data.journal, data.history, data.alerts)
            "growth", "analysis", "watchlist", "knowledge" -> OracleSimpleModule(
                host,
                moduleTitle,
                onWatchlistTickerClick = { ticker -> openWatchlistTicker(ticker) }
            ).render(actions = data.actions, knowledge = data.knowledge, positions = data.positions, history = data.history)
        }

    }

    private fun openWatchlistTicker(ticker: String) {
        val normalized = ticker.trim().uppercase(java.util.Locale.US)
        if (normalized.isBlank()) return
        OracleSimpleModule.setTickerDraft(normalized)
        openModule("analysis")
    }

    private fun handleBack() {
        if (currentModule != null) showHub() else finish()
    }

    private fun showGrowthCalculationError(error: Throwable) {
        root.removeAllViews()
        val box = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            gravity = Gravity.CENTER
            setPadding(dp(32), dp(32), dp(32), dp(32))
            setBackgroundColor(Color.rgb(3, 5, 12))
        }
        box.addView(TextView(this).apply {
            text = "GROWTH"
            textSize = 24f
            typeface = Typeface.DEFAULT_BOLD
            gravity = Gravity.CENTER
            setTextColor(Color.WHITE)
        })
        box.addView(TextView(this).apply {
            text = "Growth calculation did not finish.\n\n${error.message ?: error.javaClass.simpleName}"
            textSize = 15f
            gravity = Gravity.CENTER
            setTextColor(Color.LTGRAY)
            setPadding(0, dp(18), 0, dp(18))
        })
        box.addView(Button(this).apply {
            text = "RETRY"
            setOnClickListener { openModule("growth") }
        })
        box.addView(Button(this).apply {
            text = "BACK TO ORACLE"
            setOnClickListener { showHub() }
        })
        root.addView(box, FrameLayout.LayoutParams(-1, -1))
    }

    private fun showModuleError(key: String, error: Throwable) {
        root.removeAllViews()
        val box = LinearLayout(this).apply { orientation = LinearLayout.VERTICAL; gravity = Gravity.CENTER; setPadding(dp(32), dp(32), dp(32), dp(32)); setBackgroundColor(Color.rgb(3, 5, 12)) }
        box.addView(TextView(this).apply { text = "ORACLE  •  ${titles[key] ?: key.uppercase()}"; textSize = 22f; gravity = Gravity.CENTER; setTextColor(Color.WHITE) })
        box.addView(TextView(this).apply { text = "The module could not be loaded.\n\n${error.message ?: error.javaClass.simpleName}"; textSize = 16f; gravity = Gravity.CENTER; setTextColor(Color.LTGRAY); setPadding(0, dp(24), 0, dp(24)) })
        box.addView(Button(this).apply { text = "RETRY"; setOnClickListener { openModule(key) } })
        box.addView(Button(this).apply { text = "BACK TO ORACLE"; setOnClickListener { showHub() } })
        root.addView(box, FrameLayout.LayoutParams(-1, -1))
    }

    private fun showFatalError(title: String, error: Throwable) {
        root.removeAllViews()
        root.addView(TextView(this).apply { text = "$title\n\n${error.message ?: error.javaClass.simpleName}"; textSize = 17f; gravity = Gravity.CENTER; setTextColor(Color.WHITE); setPadding(dp(32), dp(32), dp(32), dp(32)) }, FrameLayout.LayoutParams(-1, -1))
    }

    private fun dp(v: Int) = (v * resources.displayMetrics.density).toInt()

    @Suppress("DEPRECATION")
    override fun onBackPressed() { handleBack() }
}
