from pathlib import Path
import re

ENGINE = Path("app/src/main/java/ro/alintudor/oracle/core/OracleGrowthEngine.kt")
SECTOR = Path("app/src/main/java/ro/alintudor/oracle/core/OracleSectorAllocation.kt")
GROWTH_UI = Path("app/src/main/java/ro/alintudor/oracle/nativeui/OracleGrowthModule.kt")

engine = ENGINE.read_text(encoding="utf-8")
weights_line = '    private val weights=mapOf("SHORT" to intArrayOf(21,18,18,12,16,12,3,4,4,2,2,1),"MEDIUM" to intArrayOf(12,12,12,16,12,9,9,5,5,6,5,4),"LONG" to intArrayOf(6,6,6,19,7,9,18,4,4,9,7,2))'
engine, n = re.subn(r'^\s*private val weights=.*$', weights_line, engine, count=1, flags=re.M)
if n != 1:
    raise SystemExit("Growth weights declaration not found")
if 'val correctedAllocation=OracleSectorAllocation.apply(pick.allocation,sector)' not in engine:
    raise SystemExit("Allocation-only sector correction anchor not found")
if 'correctedWeights=weights[h]!!.copyOf()' not in engine:
    raise SystemExit("Displayed Growth weights anchor not found")
if 'private fun horizonScore' not in engine or 'val w=weights[h]!!' not in engine:
    raise SystemExit("12-factor Growth scoring anchor not found")

# Allocation is continuous through the calculation and rounded only once to
# the user-facing 0.1% precision. Never quantize the base allocation to 0.5%.
if '.roundToHalf()' in engine:
    raise SystemExit("Growth allocation still contains premature 0.5% rounding")
if 'kotlin.math.round(it*10.0)/10.0' not in engine:
    raise SystemExit("Continuous 0.1% base allocation rule not found")
ENGINE.write_text(engine, encoding="utf-8")

# Sector correction remains an allocation-only multiplier. The final displayed
# allocation is rounded to exactly one decimal place, so values such as 4.7,
# 4.8, 4.3, etc. are possible rather than being restricted to a 0.025% grid.
SECTOR.write_text('''package ro.alintudor.oracle.core

/** V5.9.7 sector correction: allocation only, never a 13th score factor. */
object OracleSectorAllocation {
    private const val MIN_FACTOR = 0.50
    private const val MAX_FACTOR = 1.25

    fun factorFor(sector: String?): Double {
        val s = sector?.trim()?.lowercase() ?: return 1.0
        return when {
            s.contains("biotech") || s.contains("biotechnology") -> 0.750
            s.contains("semiconductor") || s.contains("eda") -> 0.900
            s.contains("fintech") || s.contains("financial technology") -> 0.900
            s.contains("cybersecurity") || s.contains("cyber") -> 0.900
            s.contains("artificial intelligence") || s == "ai" || s.contains("ai /") || s.contains("/ ai") -> 0.850
            s.contains("healthcare defensive") || s.contains("defensive healthcare") -> 1.050
            s.contains("healthcare") || s.contains("health care") -> 1.050
            s.contains("industr") -> 1.000
            s.contains("utilities") -> 1.100
            else -> 1.000
        }.coerceIn(MIN_FACTOR, MAX_FACTOR)
    }

    fun apply(baseAllocation: Double, sector: String?): Double =
        kotlin.math.round((baseAllocation * factorFor(sector)).coerceIn(0.0, 8.0) * 10.0) / 10.0

    fun correctedWeights(base: IntArray, sector: String?): IntArray = base.copyOf()
}
''', encoding="utf-8")

# Do not preload or display intermediate historical Growth work data.
# The current snapshot is generated by OracleLocalProcessor and rendered only
# for the current T0. Legacy journal contents remain unused.
ui = GROWTH_UI.read_text(encoding="utf-8")
ui, n_record = re.subn(r'\n\s*journalStore\.record\(items\)', '', ui, count=1)
ui, n_history = re.subn(r'\n\s*addHistory\(journalStore\.load\(\)\)', '', ui, count=1)
if n_record != 1:
    raise SystemExit("Growth journal record anchor not found")
if n_history != 1:
    raise SystemExit("Growth historical preload anchor not found")
GROWTH_UI.write_text(ui, encoding="utf-8")

expected = [
    "21,18,18,12,16,12,3,4,4,2,2,1",
    "12,12,12,16,12,9,9,5,5,6,5,4",
    "6,6,6,19,7,9,18,4,4,9,7,2",
]
for value in expected:
    if value not in engine:
        raise SystemExit(f"Missing authoritative Growth weights: {value}")
print("V5.9.7 Growth reference rules validated; allocation continuous with final 0.1% display precision; legacy Growth journal disabled")
