from pathlib import Path
import re

E=Path('app/src/main/java/ro/alintudor/oracle/core/OracleGrowthEngine.kt')
M=Path('app/src/main/java/ro/alintudor/oracle/core/OracleMarketData.kt')
s=E.read_text(encoding='utf-8')
if 'TARGET_UNIVERSE_SIZE=500' not in s:
    s=s.replace('private val universe = ', 'private val fallbackUniverse = ', 1)
    i=s.index('    private data class C')
    support='''    private const val UNIVERSE_URL="https://raw.githubusercontent.com/datasets/s-and-p-500-companies/main/data/constituents.csv"\n    private const val TARGET_UNIVERSE_SIZE=500\n    @Volatile private var cachedUniverse:List<String>?=null\n    @Volatile private var cachedUniverseSectors:Map<String,String> = emptyMap()\n    @Volatile private var cachedUniverseNames:Map<String,String> = emptyMap()\n    private fun loadUniverse():List<String>{\n        cachedUniverse?.let{if(it.size>=TARGET_UNIVERSE_SIZE)return it}\n        val loaded=runCatching{\n            val c=(URL(UNIVERSE_URL).openConnection() as HttpURLConnection).apply{requestMethod="GET";connectTimeout=1500;readTimeout=2500;setRequestProperty("User-Agent","Oracle-Stock-Intelligence/1.0")}\n            val text=c.inputStream.bufferedReader().use{it.readText()};c.disconnect()\n            val sm=linkedMapOf<String,String>();val nm=linkedMapOf<String,String>();val seenCompanies=linkedSetOf<String>()\n            val csvRegex=Regex("(?:^|,)(?:\\\"([^\\\"]*)\\\"|([^,]*))")\n            val syms=text.lineSequence().drop(1).mapNotNull{line->\n                val p=csvRegex.findAll(line).map{it.groupValues[1].ifBlank{it.groupValues[2]}}.toList()\n                val t=p.getOrNull(0)?.trim()?.uppercase(Locale.US).orEmpty();val name=p.getOrNull(1)?.trim().orEmpty();val sector=p.getOrNull(2)?.trim().orEmpty()\n                if(!t.matches(Regex("[A-Z]{1,5}([.-][A-Z])?"))||name.isBlank()||!seenCompanies.add(name)) null else {nm[t]=name;if(sector.isNotBlank())sm[t]=sector;t}\n            }.take(TARGET_UNIVERSE_SIZE).toList()\n            cachedUniverseSectors=sm.filterKeys{it in syms};cachedUniverseNames=nm.filterKeys{it in syms};syms\n        }.getOrDefault(emptyList())\n        if(loaded.size<TARGET_UNIVERSE_SIZE) throw IllegalStateException("S&P 500 company universe unavailable: ${loaded.size}")\n        cachedUniverse=loaded;return loaded\n    }\n\n'''
    s=s[:i]+support+s[i:]
old='''        val byTicker=seed.associateBy{it.ticker.uppercase(Locale.US)}\n        val candidates=mutableListOf<C>()\n        for(ticker in universe.distinct()){val candles=OracleMarketData.fetchDaily(ticker,"1y");if(candles.size<60)continue;evaluate(ticker,candles)?.let{candidates+=it}}\n        if(candidates.isEmpty())return emptyList()'''
new='''        val byTicker=seed.associateBy{it.ticker.uppercase(Locale.US)}\n        val universe=loadUniverse()\n        val candidates=java.util.concurrent.ConcurrentLinkedQueue<C>()\n        val deadline=System.nanoTime()+10_000_000_000L\n        val pool=java.util.concurrent.Executors.newFixedThreadPool(8)\n        try{universe.chunked(100).map{batch->pool.submit{val data=OracleMarketData.fetchDailyBatch(batch,"1y");for((ticker,candles) in data)if(System.nanoTime()<deadline&&candles.size>=60)evaluate(ticker,candles)?.let{candidates.add(it)}}}.forEach{f->runCatching{f.get(10,java.util.concurrent.TimeUnit.SECONDS)}}}finally{pool.shutdownNow()}\n        if(candidates.isEmpty())return emptyList()\n        val candidateList=candidates.toList()'''
if old in s:s=s.replace(old,new,1)
s=s.replace('val technicalShortlist=candidates.sortedByDescending{it.score}.take(30)','val technicalShortlist=candidateList.sortedByDescending{it.score}.take(30)',1).replace('val enriched=candidates.map{c->','val enriched=candidateList.map{c->',1)
E.write_text(s,encoding='utf-8')
ms=M.read_text(encoding='utf-8')
if 'fun fetchDailyBatch' not in ms:
    i=ms.index('    /** Fetches OHLCV at the requested Analysis timeframe. */')
    batch='''    fun fetchDailyBatch(tickers:List<String>,range:String="1y"):Map<String,List<OracleOhlcvPoint>>{val syms=tickers.map{it.trim().uppercase()}.filter{it.isNotBlank()}.distinct();if(syms.isEmpty())return emptyMap();val u=URL("https://query1.finance.yahoo.com/v7/finance/spark?symbols=${java.net.URLEncoder.encode(syms.joinToString(","),"UTF-8")}&range=$range&interval=1d&indicators=open,high,low,close,volume");val c=(u.openConnection() as HttpURLConnection).apply{requestMethod="GET";connectTimeout=2000;readTimeout=6000;setRequestProperty("User-Agent","Oracle-Stock-Intelligence/1.0")};return try{if(c.responseCode !in 200..299)return emptyMap();val root=JSONObject(c.inputStream.bufferedReader().use{it.readText()});buildMap{for(t in syms){val z=root.optJSONObject(t)?:continue;val ts=z.optJSONArray("timestamp")?:continue;val o=z.optJSONArray("open")?:continue;val h=z.optJSONArray("high")?:continue;val l=z.optJSONArray("low")?:continue;val cl=z.optJSONArray("close")?:continue;val v=z.optJSONArray("volume");val rows=ArrayList<OracleOhlcvPoint>(ts.length());for(j in 0 until ts.length()){val oo=o.optDouble(j,Double.NaN);val hh=h.optDouble(j,Double.NaN);val ll=l.optDouble(j,Double.NaN);val cc=cl.optDouble(j,Double.NaN);if(oo.isFinite()&&hh.isFinite()&&ll.isFinite()&&cc.isFinite()&&hh>0&&ll>0&&cc>0)rows+=OracleOhlcvPoint(ts.optLong(j)*1000L,oo,hh,ll,cc,v?.optDouble(j,0.0)?:0.0)};if(rows.isNotEmpty())put(t,rows.sortedBy{it.timestamp})}}}catch(_:Exception){emptyMap()}finally{c.disconnect()}}\n\n'''
    M.write_text(ms[:i]+batch+ms[i:],encoding='utf-8')
